/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratorio01;

import clases.cajero;
import clases.cliente;
import clases.producto;
import clases.transaccion;
import com.orsoncharts.plot.PiePlot3D;
import java.awt.Color;
import static java.lang.System.out;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.math3.stat.descriptive.DescriptiveStatistics;
import org.apache.commons.math3.util.IntegerSequence;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author monica
 */
public class index extends javax.swing.JFrame {

        //INICIO DE VARIABLES
        ArrayList<ArrayList<String>> lEncabezados = new ArrayList<ArrayList<String>>();
        ArrayList<Double> pagos = new ArrayList<Double>();
        Double totalTemp = 0.0;
        Double faltanteTemp = 0.0;
        public Boolean noExiste=false;
        //STRING ARRAYFAUNDER
        String[] encabezadosArray ={
        "Clientes",
        "Productos",
        "Cajeros",
        "Transacciones"
        };
        
        // ARRAYS DE CLASES
        ArrayList<cliente> listaClientes = new ArrayList<cliente>();
        ArrayList<producto> listaProductos = new ArrayList<producto>();
        ArrayList<cajero> listaCajeros = new ArrayList<cajero>();
        ArrayList<transaccion> listaTransacciones = new ArrayList<transaccion>();
        
    /**
     * Creates new form index
     */
    public index() {
        initComponents();
        //0 clientes
        ArrayList<String> EncabezadoCliente = new ArrayList<String>();
        EncabezadoCliente.add("Nombre");
        EncabezadoCliente.add("Dui");
        //1 Producto
        ArrayList<String> EncabezadoProducto = new ArrayList<String>();
        EncabezadoProducto.add("Nombre");
        EncabezadoProducto.add("Precio");
        //2 cajero
        ArrayList<String> EncabezadoCajero = new ArrayList<String>();
        EncabezadoCajero.add("Nombre");
        EncabezadoCajero.add("Sucursal");
        //3 Transacciones
        ArrayList<String> EncabezadoTransacciones = new ArrayList<String>();
        EncabezadoTransacciones.add("cliente");
        EncabezadoTransacciones.add("cajero");
        EncabezadoTransacciones.add("producto");
        EncabezadoTransacciones.add("precio");
        EncabezadoTransacciones.add("monto");
        // agregar arrayList al array padre lEncabezados
        lEncabezados.add(EncabezadoCliente);
        lEncabezados.add(EncabezadoProducto);
        lEncabezados.add(EncabezadoCajero);
        lEncabezados.add(EncabezadoTransacciones);
        //Inicializacion principal de tablas
        this.mockingData();
        this.setDeTablas();
        this.llenarComboBoxes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comercialTabs = new javax.swing.JTabbedPane();
        tabTransacciones = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        cbClientes = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        spMonto = new javax.swing.JSpinner();
        lblDui = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        cbProductos = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        btnAgregarPago = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        tbSucursalCajero = new javax.swing.JComboBox<>();
        cbCajeros = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableTransacciones = new javax.swing.JTable();
        jPanel19 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblMinimo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblMaximo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblAvg = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblStado = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblFaltante = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        tabClientes = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableClientes = new javax.swing.JTable();
        jPanel20 = new javax.swing.JPanel();
        txtClienteAgregar = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnAgregarClienteFormulario2 = new javax.swing.JButton();
        txtDuiAgregar = new javax.swing.JTextField();
        tabProductos = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        txtNombreProducto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnProductoAgregarFormulario = new javax.swing.JButton();
        spPrecio = new javax.swing.JSpinner();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableProductos = new javax.swing.JTable();
        tabCajeros = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        txtNombreCajero = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnAgregarClienteFormulario1 = new javax.swing.JButton();
        cbComercialesCajeroAgregar = new javax.swing.JComboBox<>();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableCajeros = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Comercial", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jPanel13.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 0)));

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        jButton1.setBackground(new java.awt.Color(51, 153, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cbClientes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbClientesItemStateChanged(evt);
            }
        });

        jLabel8.setText("Monto:");

        jLabel15.setText("Dui:");

        spMonto.setModel(new javax.swing.SpinnerNumberModel(0.01d, 0.01d, null, 1.0d));

        lblDui.setText("000000-0");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbClientes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(lblDui)
                        .addGap(0, 100, Short.MAX_VALUE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spMonto)))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lblDui))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(spMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder("Producto"));

        jButton3.setBackground(new java.awt.Color(51, 153, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Agregar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cbProductos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbProductosItemStateChanged(evt);
            }
        });

        jLabel10.setText("Precio:");

        lblPrecio.setText("$0.00");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(cbProductos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(lblPrecio)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblPrecio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));

        btnAgregarPago.setBackground(new java.awt.Color(51, 153, 0));
        btnAgregarPago.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarPago.setText("Agregar Pago");
        btnAgregarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPagoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregarPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btnAgregarPago)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder("Cajero"));

        jButton2.setBackground(new java.awt.Color(51, 153, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tbSucursalCajero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Centro", "Mercadito", "La 31", "La 25" }));
        tbSucursalCajero.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tbSucursalCajeroItemStateChanged(evt);
            }
        });
        tbSucursalCajero.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tbSucursalCajeroPropertyChange(evt);
            }
        });

        jLabel12.setText("Comercial:");

        jLabel14.setText("Cajero");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel12))
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tbSucursalCajero, 0, 95, Short.MAX_VALUE)
                            .addComponent(cbCajeros, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(6, 6, 6))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbSucursalCajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder("Transacciones"));

        tableTransacciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableTransacciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTransaccionesMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tableTransacciones);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado Pago"));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("PAGO MINIMO: ");

        lblMinimo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMinimo.setText("$0.00");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("PAGO MAXIMO: ");

        lblMaximo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMaximo.setText("$0.00");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Total Pago:");

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTotal.setText("$0.00");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("AVG:");

        lblAvg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAvg.setText("$0.00");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("ESTADO:");

        lblStado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblStado.setText("NaN");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("FALTANTE:");

        lblFaltante.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFaltante.setText("$0.00");

        jButton4.setBackground(new java.awt.Color(0, 102, 255));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("STATS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel19Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel19Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAvg, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel19Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblMaximo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel19Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel19Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFaltante, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(70, Short.MAX_VALUE))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(lblStado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18))))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblMinimo))
                .addGap(25, 25, 25)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblMaximo))
                .addGap(18, 18, 18)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblTotal))
                .addGap(18, 18, 18)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblAvg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(lblFaltante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lblStado)
                    .addComponent(jButton4))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout tabTransaccionesLayout = new javax.swing.GroupLayout(tabTransacciones);
        tabTransacciones.setLayout(tabTransaccionesLayout);
        tabTransaccionesLayout.setHorizontalGroup(
            tabTransaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabTransaccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabTransaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tabTransaccionesLayout.createSequentialGroup()
                        .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        tabTransaccionesLayout.setVerticalGroup(
            tabTransaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabTransaccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(tabTransaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        comercialTabs.addTab("Transacciones", tabTransacciones);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clientes Agregados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        tableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableClientes);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cajeros formulario", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        txtClienteAgregar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Nombre:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Dui:");

        btnAgregarClienteFormulario2.setBackground(new java.awt.Color(0, 204, 0));
        btnAgregarClienteFormulario2.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarClienteFormulario2.setText("AGREGAR CLIENTE");
        btnAgregarClienteFormulario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClienteFormulario2ActionPerformed(evt);
            }
        });

        txtDuiAgregar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btnAgregarClienteFormulario2)
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDuiAgregar))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtClienteAgregar)))
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClienteAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(53, 53, 53)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtDuiAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addComponent(btnAgregarClienteFormulario2)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout tabClientesLayout = new javax.swing.GroupLayout(tabClientes);
        tabClientes.setLayout(tabClientesLayout);
        tabClientesLayout.setHorizontalGroup(
            tabClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tabClientesLayout.setVerticalGroup(
            tabClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        comercialTabs.addTab("Clientes", tabClientes);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Producto formulario", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        txtNombreProducto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Precio:");

        btnProductoAgregarFormulario.setBackground(new java.awt.Color(0, 204, 0));
        btnProductoAgregarFormulario.setForeground(new java.awt.Color(255, 255, 255));
        btnProductoAgregarFormulario.setText("AGREGAR PRODUCTO");
        btnProductoAgregarFormulario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoAgregarFormularioActionPerformed(evt);
            }
        });

        spPrecio.setModel(new javax.swing.SpinnerNumberModel(0.01d, 0.01d, null, 1.0d));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreProducto))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(spPrecio)))
                .addContainerGap())
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btnProductoAgregarFormulario)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(55, 55, 55)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addComponent(btnProductoAgregarFormulario)
                .addGap(33, 33, 33))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Productos Agregados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        tableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProductosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableProductos);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout tabProductosLayout = new javax.swing.GroupLayout(tabProductos);
        tabProductos.setLayout(tabProductosLayout);
        tabProductosLayout.setHorizontalGroup(
            tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tabProductosLayout.setVerticalGroup(
            tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        comercialTabs.addTab("Productos", tabProductos);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cajeros formulario", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        txtNombreCajero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Nombre:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Comercial:");

        btnAgregarClienteFormulario1.setBackground(new java.awt.Color(0, 204, 0));
        btnAgregarClienteFormulario1.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarClienteFormulario1.setText("AGREGAR CAJERO");
        btnAgregarClienteFormulario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClienteFormulario1ActionPerformed(evt);
            }
        });

        cbComercialesCajeroAgregar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Centro", "Mercadito", "La 31", "La 25" }));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btnAgregarClienteFormulario1)
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbComercialesCajeroAgregar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreCajero)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(55, 55, 55)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbComercialesCajeroAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addComponent(btnAgregarClienteFormulario1)
                .addGap(33, 33, 33))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cajeros Agregados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        tableCajeros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableCajeros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCajerosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableCajeros);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout tabCajerosLayout = new javax.swing.GroupLayout(tabCajeros);
        tabCajeros.setLayout(tabCajerosLayout);
        tabCajerosLayout.setHorizontalGroup(
            tabCajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCajerosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tabCajerosLayout.setVerticalGroup(
            tabCajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabCajerosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabCajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        comercialTabs.addTab("Cajeros", tabCajeros);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comercialTabs)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(comercialTabs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductoAgregarFormularioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoAgregarFormularioActionPerformed
        if (!this.txtNombreProducto.getText().equals("") && Double.parseDouble(this.spPrecio.getValue().toString())>0.0) {
        this.cbProductos.disable();
        this.cbProductos.show(false);
        this.cbProductos.removeAllItems();
        
        this.listaProductos.add(
        new producto(this.txtNombreProducto.getText(),Double.parseDouble(this.spPrecio.getValue().toString()) )
        );
        
        this.listaProductos.forEach(producto->{
            this.cbProductos.addItem(producto.nombre);
        });
        this.cbProductos.enable();
        this.cbProductos.show(true);
        this.comercialTabs.setSelectedIndex(0);
        
        this.setDeTablas();
        }else{
            JOptionPane.showMessageDialog(null,"Ingrese un nombre de producto o un precio mayor a $0.0\nPor favor!");
        }
    }//GEN-LAST:event_btnProductoAgregarFormularioActionPerformed

    private void btnAgregarClienteFormulario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteFormulario1ActionPerformed
       if (!this.txtNombreCajero.getText().equals("") ) {
        this.cbCajeros.disable();
        this.cbCajeros.show(false);
        this.cbCajeros.removeAllItems();
        
        this.listaCajeros.add(
        new cajero(this.txtNombreCajero.getText(),this.cbComercialesCajeroAgregar.getSelectedItem().toString() )
        );
        
        this.listaCajeros.forEach(cajero->{
            this.cbCajeros.addItem(cajero.nombre);
        });
        this.cbCajeros.enable();
        this.cbCajeros.show(true);
        this.comercialTabs.setSelectedIndex(0);
        }else{
            JOptionPane.showMessageDialog(null,"Ingrese el nombre del cajero \nPor favor!");
        }    
       
        this.setDeTablas();
    }//GEN-LAST:event_btnAgregarClienteFormulario1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.comercialTabs.setSelectedIndex(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.comercialTabs.setSelectedIndex(3);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         this.comercialTabs.setSelectedIndex(2);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnAgregarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPagoActionPerformed
        
        if (!this.lblStado.getText().equals("FINALIZADO")) {
            try {
                this.reformarTablaPorClienteYProducto();
            } catch (Exception e) {
            }
            Double montoCalculado = Double.parseDouble(this.spMonto.getValue().toString());
            // totalTemp viene de la gestion que se hace en reformarTablaPorClienteYProducto();
            System.out.println("montoCalculado: "+montoCalculado+" > "+" faltaDePagar: "+this.faltanteTemp);
            if ( this.faltanteTemp>0.0 && montoCalculado > this.faltanteTemp ) { 
                // si el monto a tratar de pagar es mayor al faltante de pagar
                //entonces en montoCalculado que es lo que se registrara, se resta para dar un "vuelto"
                JOptionPane.showMessageDialog(null, "Devolucion de: $"+(montoCalculado-this.faltanteTemp));
                montoCalculado = this.faltanteTemp;
            }else if (this.faltanteTemp>0.0 && montoCalculado > Double.parseDouble(this.lblPrecio.getText()) ) {
                JOptionPane.showMessageDialog(null, "Devolucion de: $"+(montoCalculado-this.faltanteTemp));
                montoCalculado = Double.parseDouble(this.lblPrecio.getText());
            }else if (montoCalculado > Double.parseDouble(this.lblPrecio.getText())){
                JOptionPane.showMessageDialog(null, "Devolucion de: $"+(montoCalculado-Double.parseDouble(this.lblPrecio.getText())));
                montoCalculado = Double.parseDouble(this.lblPrecio.getText());
            }
            
        this.listaTransacciones.add(
        new transaccion(
                this.listaClientes.get(this.cbClientes.getSelectedIndex()),
                this.listaProductos.get(this.cbProductos.getSelectedIndex()),
                this.listaCajeros.get(this.cbCajeros.getSelectedIndex()),
                Double.parseDouble(this.lblPrecio.getText()), 
                Double.parseDouble(String.format("%.2f", montoCalculado))
                )
        );
        this.reformarTablaPorClienteYProducto();
        }
    }//GEN-LAST:event_btnAgregarPagoActionPerformed

    private void tbSucursalCajeroPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tbSucursalCajeroPropertyChange

    }//GEN-LAST:event_tbSucursalCajeroPropertyChange

    private void tbSucursalCajeroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tbSucursalCajeroItemStateChanged
        this.cbCajeros.removeAllItems();
        this.listaCajeros.forEach(cajero->{
            if (cajero.sucursal.equals(this.tbSucursalCajero.getSelectedItem().toString())) {
                this.cbCajeros.addItem(cajero.nombre);
            }
        });
    }//GEN-LAST:event_tbSucursalCajeroItemStateChanged

    private void cbClientesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbClientesItemStateChanged

        try {
            this.lblStado.setText("");
            this.lblFaltante.setText("");
            this.lblAvg.setText("");
            System.out.println("index Cliente: "+this.cbClientes.getSelectedIndex());
            this.lblDui.setText(this.listaClientes.get(this.cbClientes.getSelectedIndex()).dui);
            this.reformarTablaPorClienteYProducto();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cbClientesItemStateChanged

    private void cbProductosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbProductosItemStateChanged
        

        try {
            this.lblStado.setText("");
            this.lblFaltante.setText("");
            this.lblAvg.setText("");
            this.lblPrecio.setText(this.listaProductos.get(this.cbProductos.getSelectedIndex()).precio.toString());
            this.reformarTablaPorClienteYProducto();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cbProductosItemStateChanged

    private void tableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableClientesMouseClicked
        try {
            this.cbClientes.setSelectedIndex(this.tableClientes.getSelectedRow());
            this.comercialTabs.setSelectedIndex(0);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tableClientesMouseClicked

    private void tableTransaccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTransaccionesMouseClicked

    }//GEN-LAST:event_tableTransaccionesMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.calcularCuartil();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnAgregarClienteFormulario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteFormulario2ActionPerformed
        if (!this.txtClienteAgregar.getText().equals("") && !this.txtDuiAgregar.getText().equals("") ) {
            Boolean existe = false;
            for (cliente cliente : listaClientes) {
                if (cliente.dui == this.txtDuiAgregar.getText()) {
                    existe=true;
                }
            }
            if (!existe) {
                this.cbClientes.disable();
                this.cbClientes.show(false);
                this.cbClientes.removeAllItems();

                this.listaClientes.add(
                new cliente(this.txtClienteAgregar.getText(), this.txtDuiAgregar.getText() )
                );

                this.listaClientes.forEach(cliente->{
                    this.cbClientes.addItem(cliente.nombre);
                });
                this.cbClientes.enable();
                this.cbClientes.show(true);
                this.comercialTabs.setSelectedIndex(0);
                this.setDeTablas();   
                this.txtDuiAgregar.setText("");
                this.txtClienteAgregar.setText("");
            }else{
            JOptionPane.showMessageDialog(null,"Ingrese un numero de Dui diferente \nPor favor!");
            }
        }else{
            JOptionPane.showMessageDialog(null,"Ingrese el nombre del Cliente o el numero de dui \nPor favor!");
        }
    }//GEN-LAST:event_btnAgregarClienteFormulario2ActionPerformed

    private void tableProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProductosMouseClicked
        try {
            this.cbProductos.setSelectedIndex(this.tableProductos.getSelectedRow());
            this.comercialTabs.setSelectedIndex(0);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tableProductosMouseClicked

    private void tableCajerosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCajerosMouseClicked
        try {
            this.cbCajeros.setSelectedIndex(this.tableCajeros.getSelectedRow());
            this.comercialTabs.setSelectedIndex(0);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tableCajerosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }
    
    /**
     * FUNCIONES COMUNES
     */
    
    public void llenarTabla(String tablaAllenar){ // tomaremos el nombre de la tabla a llenar
    DefaultTableModel mdTabla = new DefaultTableModel();
    int tablaEncabezadosIndex = Arrays.asList(encabezadosArray).indexOf(tablaAllenar);
    ArrayList<String>lCabeza = lEncabezados.get(tablaEncabezadosIndex);
        for (String object : lCabeza) {
            mdTabla.addColumn(object);
        }
        
        switch(tablaAllenar){
            case "Clientes":
            tableClientes.setModel(mdTabla);
            listaClientes.forEach(rows->{
                String [] rowsClientes = {
                   rows.nombre,
                   rows.dui
                };
                mdTabla.addRow(rowsClientes);
             });
            tableClientes.setModel(mdTabla);
            break;
            case "Productos":
            tableProductos.setModel(mdTabla);
            listaProductos.forEach(rows->{
                String [] rowsClientes = {
                   rows.nombre,
                   rows.precio.toString()
                };
                mdTabla.addRow(rowsClientes);
             });
            tableProductos.setModel(mdTabla);
            break;
            case "Cajeros":
            tableCajeros.setModel(mdTabla);
            listaCajeros.forEach(rows->{
                String [] rowsClientes = {
                   rows.nombre,
                   rows.sucursal
                };
                mdTabla.addRow(rowsClientes);
             });
            tableCajeros.setModel(mdTabla);
            break;
            case "Transacciones":
            tableTransacciones.setModel(mdTabla);
            listaTransacciones.forEach(rows->{
                String [] rowsClientes = {
                   rows.cliente.nombre,
                   rows.cajero.nombre,
                   rows.producto.nombre,
                   rows.precio.toString(),
                   rows.monto.toString()
                };
                mdTabla.addRow(rowsClientes);
             });
            tableTransacciones.setModel(mdTabla);
            break;
        }
    
    }
    
    public void setDeTablas(){
    
        for(String tabla : encabezadosArray){
            this.llenarTabla(tabla);
            
        }
        
    }

    public void mockingData(){
    
        this.listaClientes.add(new cliente("Fabricio Ramirez", "1111111-1"));
        this.listaClientes.add(new cliente("Dennis Almidar", "0202020-0"));
        this.listaClientes.add(new cliente("Tito ", "3333323-3"));
        
        
        this.listaProductos.add(new producto("Automovil 2019",15700.00 ));
        this.listaProductos.add(new producto("Motocicleta 2019",18020.00 ));
        this.listaProductos.add(new producto("Pantalla 50'",500.00 ));
        this.listaProductos.add(new producto("Laptop ",650.00 ));
        
        this.listaCajeros.add(new cajero("Gisela", "La 25"));
        this.listaCajeros.add(new cajero("Olga", "Mercadito"));
        this.listaCajeros.add(new cajero("Mariela", "La 31"));
        this.listaCajeros.add(new cajero("Ursula", "Centro"));
        
        
    }
    
    
    public void llenarComboBoxes(){
        
        for (cliente cliente : listaClientes) {
            this.cbClientes.addItem(cliente.nombre);
        }
        this.cbProductos.removeAllItems();
        listaProductos.forEach(producto->{
            cbProductos.addItem(producto.nombre+" $:"+producto.precio);
        });
        this.cbCajeros.removeAllItems();
        listaCajeros.forEach(cajero->{
            cbCajeros.addItem(cajero.nombre+", "+cajero.sucursal);
        });
        
    }
    
    public void reformarTablaPorClienteYProducto(){
        this.lblMaximo.setText("");
        this.lblMinimo.setText("");
        this.lblTotal.setText("");
    DefaultTableModel mdTabla = new DefaultTableModel();
    ArrayList<String>lCabeza = lEncabezados.get(3);
        for (String object : lCabeza) {
            mdTabla.addColumn(object);
        }
        this.pagos = new ArrayList<Double>();
        String productoNombre = this.listaProductos.get(this.cbProductos.getSelectedIndex()).nombre;
    tableTransacciones.setModel(mdTabla);
    listaTransacciones.forEach(rows->{
        if(this.lblDui.getText().equals(rows.cliente.dui) && productoNombre.equals(rows.producto.nombre)){
        String [] rowsClientes = {
           rows.cliente.nombre,
           rows.cajero.nombre,
           rows.producto.nombre,
           rows.precio.toString(),
           rows.monto.toString()
        };
        //tomamnos los montos temporales en un arrayList
        pagos.add(rows.monto);
        mdTabla.addRow(rowsClientes);
        }
     });
    
    tableTransacciones.setModel(mdTabla);
        
    //set minimo maximo avg total de pago
    //INFORMACION  https://www.javacodeexamples.com/find-minimum-maximum-value-in-arraylist/1010
    this.lblMaximo.setText(Collections.max(pagos).toString());
    this.lblMinimo.setText(Collections.min(pagos).toString());
    this.lblStado.setText("");
    this.lblFaltante.setText("");
    this.lblAvg.setText("");
    
        this.totalTemp = 0.0;
        for (Double pago : pagos) {
            totalTemp+=pago;
        }
    this.lblTotal.setText(String.format("%.2f",totalTemp));
    Double avgTemp = totalTemp/pagos.size();
    this.lblAvg.setText(String.format("%.2f",avgTemp));
    this.faltanteTemp = Double.parseDouble(this.lblPrecio.getText())-totalTemp;
        if (faltanteTemp>=0.00) {
            this.lblFaltante.setText(String.format("%.2f",faltanteTemp));
        }else{
            this.lblFaltante.setText("0.00");
        }
        /*Double tempTt = (Double.parseDouble(this.spMonto.getValue().toString())-faltanteTemp);
        if( tempTt < 0.0 ){
            JOptionPane.showMessageDialog(null, "Devolucion de dinero: $"+tempTt);
        }*/
    if (totalTemp >= Double.parseDouble(this.lblPrecio.getText())) {
        this.lblStado.setText("FINALIZADO");
        this.lblStado.setForeground(Color.GREEN);
    }else{
        this.lblStado.setText("FALTA");
        this.lblStado.setForeground(Color.RED);
    }

    }
    //AQUI SE CALCULA LOS PERCENTILES
    public void calcularCuartil(){
        DescriptiveStatistics stats = new DescriptiveStatistics();
        ArrayList<Double> pagosTemp = this.pagos;
        this.pagos.forEach(pago->{
            stats.addValue(pago);
        });
        Double q1 = stats.getPercentile(25);
        Double q2 = stats.getPercentile(50);
        Double q3 = stats.getPercentile(75);
        System.out.println(q1+" "+q2+" "+q3);
        Integer[] ql = {0,0,0,0};
        for (Double pago : pagosTemp) {
            if (pago>=0 && pago <=q1) {
                ql[0]+=1;
            }else if (pago>=q1 && pago<=q2) {
                ql[1]+=1;
            }else if (pago>=q2 && pago<=q3) {
                ql[2]+=1;
            }else if (pago>=q3 && pago<=stats.getMax()) {
                ql[3]+=1;
            }
        }

        DefaultPieDataset pieDataset = new DefaultPieDataset();
        pieDataset.setValue("Cuartil #1 (0-25) : "+ql[0],ql[0]);
        pieDataset.setValue("Cuartil #2 (25-50): "+ql[1],ql[1]);
        pieDataset.setValue("Cuartil #3 (50-75): "+ql[2],ql[2]);
        pieDataset.setValue("Cuartil #4 (75-100): "+ql[3],ql[3]);
        JFreeChart chart = ChartFactory.createPieChart("Cuartiles", pieDataset, true,true,true);
        ChartFrame frame = new ChartFrame("Cuartiles",chart);
        frame.setVisible(true);
        frame.setSize(450, 500);
       
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarClienteFormulario1;
    private javax.swing.JButton btnAgregarClienteFormulario2;
    private javax.swing.JButton btnAgregarPago;
    private javax.swing.JButton btnProductoAgregarFormulario;
    private javax.swing.JComboBox<String> cbCajeros;
    private javax.swing.JComboBox<String> cbClientes;
    private javax.swing.JComboBox<String> cbComercialesCajeroAgregar;
    private javax.swing.JComboBox<String> cbProductos;
    private javax.swing.JTabbedPane comercialTabs;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblAvg;
    private javax.swing.JLabel lblDui;
    private javax.swing.JLabel lblFaltante;
    private javax.swing.JLabel lblMaximo;
    private javax.swing.JLabel lblMinimo;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblStado;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JSpinner spMonto;
    private javax.swing.JSpinner spPrecio;
    private javax.swing.JPanel tabCajeros;
    private javax.swing.JPanel tabClientes;
    private javax.swing.JPanel tabProductos;
    private javax.swing.JPanel tabTransacciones;
    private javax.swing.JTable tableCajeros;
    private javax.swing.JTable tableClientes;
    private javax.swing.JTable tableProductos;
    private javax.swing.JTable tableTransacciones;
    private javax.swing.JComboBox<String> tbSucursalCajero;
    private javax.swing.JTextField txtClienteAgregar;
    private javax.swing.JTextField txtDuiAgregar;
    private javax.swing.JTextField txtNombreCajero;
    private javax.swing.JTextField txtNombreProducto;
    // End of variables declaration//GEN-END:variables
}
